# Generated by Django 5.2.5 on 2025-08-22 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organisation', 'verbose_name_plural': 'Organisations'},
        ),
    ]
