# Generated by Django 5.2.5 on 2025-08-22 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_alter_organization_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
    ]
