# Generated by Django 5.2.5 on 2025-08-18 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province_state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='CA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('doing_business_as', models.CharField(blank=True, max_length=255)),
                ('jurisdiction', models.CharField(choices=[('CBCA', 'Fédéral (CBCA)'), ('QC', 'Québec (LSAQ)')], max_length=10)),
                ('incorporation_number', models.CharField(blank=True, max_length=50)),
                ('business_number', models.CharField(blank=True, max_length=15)),
                ('fiscal_year_end_month', models.PositiveSmallIntegerField(default=12)),
                ('fiscal_year_end_day', models.PositiveSmallIntegerField(default=31)),
                ('language_pref', models.CharField(default='fr', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corporations', to='orgs.organization')),
                ('records_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records_for', to='corps.address')),
                ('registered_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_for', to='corps.address')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('jurisdiction', models.CharField(blank=True, max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corps.address')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PERSON', 'Person'), ('ENTITY', 'Entity')], max_length=10)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corps.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='corps.corporation')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corps.party')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='corps.corporation')),
                ('residential_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corps.address')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corps.party')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=100)),
                ('tax_residence', models.CharField(blank=True, max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corps.address')),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corps.person'),
        ),
    ]
