# Generated by Django 5.2.5 on 2025-08-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corps', '0002_add_sharelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='jurisdiction',
            field=models.CharField(choices=[('CBCA', 'Fédéral (LCSA)'), ('QC', 'Québec (LSAQ)')], max_length=10),
        ),
    ]
