# Generated by Django 5.2.5 on 2025-08-22 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corps', '0003_alter_corporation_jurisdiction'),
        ('orgs', '0002_alter_organization_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Adresse', 'verbose_name_plural': 'Adresses'},
        ),
        migrations.AlterModelOptions(
            name='corporation',
            options={'verbose_name': 'Société par actions', 'verbose_name_plural': 'Sociétés par actions'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Administrateur', 'verbose_name_plural': 'Administrateurs'},
        ),
        migrations.AlterModelOptions(
            name='officer',
            options={'verbose_name': 'Dirigeant', 'verbose_name_plural': 'Dirigeants'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'Individu', 'verbose_name_plural': 'Individus'},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Canada', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line1',
            field=models.CharField(max_length=255, verbose_name='Adresse (ligne 1)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse (ligne 2)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province_state',
            field=models.CharField(default='Québec', max_length=100, verbose_name='Province/État'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='business_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='NE (fédéral)'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='doing_business_as',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom d’exploitation'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='fiscal_year_end_day',
            field=models.PositiveSmallIntegerField(default=31, verbose_name='Jour de fin d’exercice'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='fiscal_year_end_month',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='Mois de fin d’exercice'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='incorporation_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='NEQ'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='jurisdiction',
            field=models.CharField(choices=[('LCSA', 'Fédéral (LCSA)'), ('LSAQ', 'Québec (LSAQ)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='language_pref',
            field=models.CharField(default='Français', max_length=15, verbose_name='Langue de correspondance'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='legal_name',
            field=models.CharField(max_length=255, verbose_name='Dénomination sociale'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='records_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_for', to='corps.address'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='registered_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_for', to='corps.address', verbose_name='Siège social'),
        ),
    ]
