# Generated by Django 5.2.5 on 2025-08-22 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corps', '0004_alter_address_options_alter_corporation_options_and_more'),
        ('orgs', '0002_alter_organization_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporations', to='orgs.organization', verbose_name='Organisation'),
        ),
    ]
