# Generated by Django 5.2.5 on 2025-08-22 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corps', '0005_alter_corporation_org'),
        ('orgs', '0003_alter_organization_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.AlterModelOptions(
            name='corporation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={},
        ),
        migrations.AlterModelOptions(
            name='officer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='CA', max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='line1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='province_state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='business_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='doing_business_as',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='fiscal_year_end_day',
            field=models.PositiveSmallIntegerField(default=31),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='fiscal_year_end_month',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='incorporation_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='jurisdiction',
            field=models.CharField(choices=[('CBCA', 'Fédéral (LCSA)'), ('QC', 'Québec (LSAQ)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='language_pref',
            field=models.CharField(default='fr', max_length=5),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='legal_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corporations', to='orgs.organization'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='records_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records_for', to='corps.address'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='registered_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_for', to='corps.address'),
        ),
    ]
