# Generated by Django 5.2.5 on 2025-08-18 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CC_AR', 'Corporations Canada — rapport annuel'), ('REQ_ANNUAL', 'REQ — mise à jour annuelle'), ('REQ_EVENT', 'REQ — mise à jour événementielle'), ('ISC_UPD', 'Mise à jour ISC/BUO')], max_length=20)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('READY', 'Prêt à déposer'), ('FILED', 'Déposé'), ('REJECTED', 'Rejeté')], default='DRAFT', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corps.corporation')),
            ],
        ),
    ]
