# Generated by Django 5.2.5 on 2025-08-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
