# Generated by Django 5.2.5 on 2025-08-22 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_content_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('ARTICLES', 'Statuts/Articles'), ('BYLAWS', 'Règlement intérieur/administratif'), ('RES_SH', 'Résolution des actionnaires'), ('RES_BD', "Résolution du conseil d'administration"), ('CERT', "Certificat d'actions"), ('OTHER', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Téléversé le'),
        ),
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(default='Français', max_length=5, verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Téléversé par'),
        ),
    ]
