# Generated by Django 5.2.5 on 2025-08-22 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_options_alter_document_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('ARTICLES', 'Statuts/Articles'), ('BYLAWS', 'Règlement intérieur'), ('RES_SH', 'Résolution des actionnaires'), ('RES_BD', 'Résolution du CA'), ('CERT', "Certificat d'actions"), ('OTHER', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(default='fr', max_length=5),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
