# Generated by Django 5.2.5 on 2025-08-18 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('par_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('is_voting', models.BooleanField(default=True)),
                ('is_redeemable', models.BooleanField(default=False)),
                ('is_retractable', models.BooleanField(default=False)),
                ('transfer_restrictions', models.TextField(blank=True)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_classes', to='corps.corporation')),
            ],
        ),
        migrations.CreateModel(
            name='ShareCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('issued_on', models.DateField()),
                ('cancelled_on', models.DateField(blank=True, null=True)),
                ('reason_cancelled', models.CharField(blank=True, max_length=200)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='corps.corporation')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corps.party')),
                ('share_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registers.shareclass')),
            ],
        ),
        migrations.CreateModel(
            name='ShareIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('consideration', models.CharField(blank=True, max_length=255)),
                ('resolution_ref', models.CharField(blank=True, max_length=255)),
                ('occurred_on', models.DateField()),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corps.corporation')),
                ('share_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registers.shareclass')),
                ('to_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='corps.party')),
            ],
        ),
        migrations.CreateModel(
            name='ShareRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('occurred_on', models.DateField()),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corps.corporation')),
                ('from_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corps.party')),
                ('share_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registers.shareclass')),
            ],
        ),
        migrations.CreateModel(
            name='ShareTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('occurred_on', models.DateField()),
                ('consideration', models.CharField(blank=True, max_length=255)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corps.corporation')),
                ('from_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='corps.party')),
                ('share_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registers.shareclass')),
                ('to_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='corps.party')),
            ],
        ),
    ]
