# Generated by Django 5.2.5 on 2025-08-22 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corps', '0004_alter_address_options_alter_corporation_options_and_more'),
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharecertificate',
            options={'verbose_name': 'Certificat d’actions', 'verbose_name_plural': 'Certificats d’actions'},
        ),
        migrations.AlterModelOptions(
            name='shareclass',
            options={'verbose_name': 'Catégorie d’actions', 'verbose_name_plural': 'Catégories d’actions'},
        ),
        migrations.AlterModelOptions(
            name='shareissuance',
            options={'verbose_name': 'Émission d’actions', 'verbose_name_plural': 'Émissions d’actions'},
        ),
        migrations.AlterModelOptions(
            name='shareredemption',
            options={'verbose_name': 'Rachat d’actions', 'verbose_name_plural': 'Rachats d’actions'},
        ),
        migrations.AlterModelOptions(
            name='sharetransfer',
            options={'verbose_name': 'Transfert d’actions', 'verbose_name_plural': 'Transferts d’actions'},
        ),
        migrations.AlterField(
            model_name='sharecertificate',
            name='cancelled_on',
            field=models.DateField(blank=True, null=True, verbose_name='Date d’annulation'),
        ),
        migrations.AlterField(
            model_name='sharecertificate',
            name='corp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='corps.corporation', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='sharecertificate',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corps.party', verbose_name='Détenteur'),
        ),
        migrations.AlterField(
            model_name='sharecertificate',
            name='issued_on',
            field=models.DateField(verbose_name='Date d’émission'),
        ),
        migrations.AlterField(
            model_name='sharecertificate',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Numéro du certificat'),
        ),
        migrations.AlterField(
            model_name='sharecertificate',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quanté'),
        ),
        migrations.AlterField(
            model_name='sharecertificate',
            name='reason_cancelled',
            field=models.CharField(blank=True, max_length=200, verbose_name='Raison de l’annulation'),
        ),
        migrations.AlterField(
            model_name='sharecertificate',
            name='share_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registers.shareclass', verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='shareclass',
            name='corp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_classes', to='corps.corporation', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='shareclass',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='shareclass',
            name='is_redeemable',
            field=models.BooleanField(default=False, verbose_name='Rachetable'),
        ),
        migrations.AlterField(
            model_name='shareclass',
            name='is_retractable',
            field=models.BooleanField(default=False, verbose_name='Rachetable à la demande'),
        ),
        migrations.AlterField(
            model_name='shareclass',
            name='is_voting',
            field=models.BooleanField(default=False, verbose_name='Droit de vote'),
        ),
        migrations.AlterField(
            model_name='shareclass',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom de la catégorie'),
        ),
        migrations.AlterField(
            model_name='shareclass',
            name='transfer_restrictions',
            field=models.TextField(blank=True, verbose_name='Restrictions à l’aliénation'),
        ),
        migrations.AlterField(
            model_name='shareissuance',
            name='consideration',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contrepartie'),
        ),
        migrations.AlterField(
            model_name='shareissuance',
            name='occurred_on',
            field=models.DateField(verbose_name='Date d’émission'),
        ),
        migrations.AlterField(
            model_name='shareissuance',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='shareissuance',
            name='resolution_ref',
            field=models.CharField(blank=True, max_length=255, verbose_name='Date de la résolution'),
        ),
        migrations.AlterField(
            model_name='shareissuance',
            name='share_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registers.shareclass', verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='shareissuance',
            name='to_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='corps.party', verbose_name='Bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='shareredemption',
            name='from_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corps.party', verbose_name='Actionnaire racheté'),
        ),
        migrations.AlterField(
            model_name='shareredemption',
            name='occurred_on',
            field=models.DateField(verbose_name='Date de rachat'),
        ),
        migrations.AlterField(
            model_name='shareredemption',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='sharetransfer',
            name='consideration',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contrepartie'),
        ),
        migrations.AlterField(
            model_name='sharetransfer',
            name='from_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='corps.party', verbose_name='Cédant'),
        ),
        migrations.AlterField(
            model_name='sharetransfer',
            name='occurred_on',
            field=models.DateField(verbose_name='Date de transfert'),
        ),
        migrations.AlterField(
            model_name='sharetransfer',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='sharetransfer',
            name='to_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='corps.party', verbose_name='Cessionnaire'),
        ),
    ]
