# Generated by Django 5.2.5 on 2025-08-22 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corps', '0006_alter_address_options_alter_corporation_options_and_more'),
        ('registers', '0002_alter_sharecertificate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharecertificate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shareclass',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shareissuance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shareredemption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sharetransfer',
            options={},
        ),
        migrations.AlterField(
            model_name='sharecertificate',
            name='cancelled_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sharecertificate',
            name='corp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='corps.corporation'),
        ),
        migrations.AlterField(
            model_name='sharecertificate',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corps.party'),
        ),
        migrations.AlterField(
            model_name='sharecertificate',
            name='issued_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sharecertificate',
            name='number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sharecertificate',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sharecertificate',
            name='reason_cancelled',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sharecertificate',
            name='share_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registers.shareclass'),
        ),
        migrations.AlterField(
            model_name='shareclass',
            name='corp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_classes', to='corps.corporation'),
        ),
        migrations.AlterField(
            model_name='shareclass',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shareclass',
            name='is_redeemable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shareclass',
            name='is_retractable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shareclass',
            name='is_voting',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shareclass',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shareclass',
            name='transfer_restrictions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shareissuance',
            name='consideration',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shareissuance',
            name='occurred_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shareissuance',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='shareissuance',
            name='resolution_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shareissuance',
            name='share_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registers.shareclass'),
        ),
        migrations.AlterField(
            model_name='shareissuance',
            name='to_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='corps.party'),
        ),
        migrations.AlterField(
            model_name='shareredemption',
            name='from_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corps.party'),
        ),
        migrations.AlterField(
            model_name='shareredemption',
            name='occurred_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shareredemption',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sharetransfer',
            name='consideration',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sharetransfer',
            name='from_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='corps.party'),
        ),
        migrations.AlterField(
            model_name='sharetransfer',
            name='occurred_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sharetransfer',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sharetransfer',
            name='to_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='corps.party'),
        ),
    ]
