# Generated by Django 5.2.5 on 2025-08-18 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RESOLUTION', 'Rédaction de résolution'), ('FILING', 'Dépôt REQ/Corporations Canada'), ('MIGRATION', 'Migration livre papier'), ('OTHER', 'Autre')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('IN_PROGRESS', 'En cours'), ('WAITING', 'En attente du client'), ('DONE', 'Terminé')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corps.corporation')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_opened', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
