# Generated by Django 5.2.5 on 2025-08-21 02:03

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(upload_to=tickets.models.ticket_attachment_upload_to),
        ),
    ]
