name: CI
on: [push, pull_request]

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: System deps
        run: sudo apt-get update && sudo apt-get install -y libmagic1
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Django health check
        env:
          DJANGO_SETTINGS_MODULE: minutebooks.settings
          SECRET_KEY: dummy
        run: |
          python manage.py check
          python manage.py makemigrations --check --dry-run
